{% set name = "graphpro" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5529f4571bcf999480bdf215eae144e84626c0b72af2192fa45563cb3061e1f


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.13.0
  run:
    - python >=3.7
    - MDAnalysis >=2.4.3
    - MDAnalysisTests >=2.4.3
    - networkx >=3.1
    - pytorch >=2.0
    - pytorch_geometric >=2.0

test:
  imports:
    - graphpro
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pegerto/graphpro
  summary: 'GraphPro: a python framework for protein deep geometrical learning'
  description: |
    GraphPro is a versatile and pluggable OO python library designed for leveraging deep graph learning representations to gain
    insights into structural proteins and their conformations. With its wide range of functionalities,
    we provide a comprehensive framework for researchers and practitioners to explore and analyze complex protein structures.
  license: GPL-3.0
  license_file: LICENSE.txt
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/pegerto/graphpro

extra:
  recipe-maintainers:
    - pegerto
